import { Challenge, Question } from "./types";

export const QUESTIONS: Question[] = [
  {
    id: "qz-sql-having",
    prompt: "Which clause filters rows after aggregation in SQL?",
    options: ["WHERE", "HAVING", "QUALIFY", "FILTER"],
    answerIndex: 1,
    explanation: "WHERE filters input rows before grouping. HAVING filters the grouped result, so conditions on SUM() or COUNT() belong there.",
    category: "data",
    difficulty: "beginner",
  },
  {
    id: "qz-python-mutable-default",
    prompt: "What does this print?",
    code: "def add(x, bucket=[]):\n    bucket.append(x)\n    return bucket\n\nprint(add(1))\nprint(add(2))",
    options: ["[1] then [2]", "[1] then [1, 2]", "[1, 2] then [1, 2]", "TypeError"],
    answerIndex: 1,
    explanation: "The default list is created once when the function is defined, so it persists between calls. Use bucket=None and create the list inside the function.",
    category: "programming",
    difficulty: "intermediate",
  },
  {
    id: "qz-join-null",
    prompt: "A LEFT JOIN returns more rows than the left table has. Why?",
    options: [
      "LEFT JOIN always duplicates rows",
      "The join key is not unique in the right table",
      "NULLs in the left table multiply",
      "It is impossible",
    ],
    answerIndex: 1,
    explanation: "A left row matching three right rows produces three output rows. Check the right table's key cardinality before joining.",
    category: "data",
    difficulty: "intermediate",
  },
  {
    id: "qz-pvalue",
    prompt: "A test returns p = 0.03. What does that mean?",
    options: [
      "There is a 3% chance the null hypothesis is true",
      "There is a 97% chance the effect is real",
      "Data this extreme would occur 3% of the time if the null hypothesis were true",
      "The effect size is 3%",
    ],
    answerIndex: 2,
    explanation: "A p-value is computed assuming the null hypothesis holds. It says nothing directly about the probability of a hypothesis or the size of an effect.",
    category: "statistics",
    difficulty: "intermediate",
  },
  {
    id: "qz-pandas-copy",
    prompt: "Why can chained assignment such as df[df.a > 0]['b'] = 1 fail silently?",
    options: [
      "Boolean masks are read-only",
      "The mask returns a copy, so the write may not reach the original frame",
      "Column b must be numeric",
      "pandas forbids writing after filtering",
    ],
    answerIndex: 1,
    explanation: "Chained indexing can produce an intermediate copy. Use df.loc[df.a > 0, 'b'] = 1 so the write targets the original frame.",
    category: "data",
    difficulty: "intermediate",
  },
  {
    id: "qz-accuracy-imbalance",
    prompt: "A fraud model is 99.2% accurate on data where 0.8% of transactions are fraud. What should you suspect?",
    options: [
      "The model is excellent",
      "It may be predicting the majority class for everything",
      "The data has too many features",
      "Accuracy cannot be computed here",
    ],
    answerIndex: 1,
    explanation: "Predicting 'not fraud' always scores 99.2%. Judge imbalanced problems with recall, precision or average precision instead.",
    category: "ml",
    difficulty: "beginner",
  },
  {
    id: "qz-normalization-scale",
    prompt: "Which model is most sensitive to unscaled features?",
    options: ["Decision tree", "Random forest", "K-nearest neighbours", "Naive Bayes on counts"],
    answerIndex: 2,
    explanation: "KNN uses distances, so a feature measured in thousands dominates one measured in units. Tree splits are scale-invariant.",
    category: "ml",
    difficulty: "intermediate",
  },
  {
    id: "qz-index-order",
    prompt: "You have an index on (country, city). Which query can use it efficiently?",
    options: [
      "WHERE city = 'Hargeisa'",
      "WHERE country = 'Somalia'",
      "WHERE city = 'Hargeisa' AND ordered by nothing",
      "None of them",
    ],
    answerIndex: 1,
    explanation: "A composite index is usable from its leftmost column. Filtering on city alone skips the prefix, so the index cannot be seeked.",
    category: "data",
    difficulty: "advanced",
  },
  {
    id: "qz-temperature",
    prompt: "Lowering the sampling temperature of a language model does what?",
    options: [
      "Makes the model more accurate",
      "Concentrates probability on the highest-scoring tokens",
      "Shortens the output",
      "Reduces the context window",
    ],
    answerIndex: 1,
    explanation: "Temperature rescales the logits before sampling. Lower values make output more deterministic, which is not the same as more correct.",
    category: "ai",
    difficulty: "intermediate",
  },
  {
    id: "qz-correlation-causation",
    prompt: "Two variables correlate at r = 0.91 across 40 countries. What can you conclude?",
    options: [
      "One causes the other",
      "They move together in this sample; the cause is undetermined",
      "The relationship is linear and causal",
      "The sample is too small to compute r",
    ],
    answerIndex: 1,
    explanation: "Correlation measures co-movement. Confounding, reverse causation and selection all produce strong r without any causal link.",
    category: "statistics",
    difficulty: "beginner",
  },
];

export const CHALLENGES: Challenge[] = [
  {
    id: "ch-null-audit",
    title: "Audit a messy column in five minutes",
    brief: "Take any dataset you have and pick the least trustworthy column. Quantify exactly how broken it is before you fix anything.",
    steps: [
      "Count total rows, non-null values and distinct values.",
      "List the ten most frequent values and look for near-duplicates such as 'NA', 'n/a' and ''.",
      "Coerce to the intended type with errors='coerce' and count what fails.",
      "Write one sentence describing what a downstream user would get wrong today.",
    ],
    category: "data",
    difficulty: "beginner",
  },
  {
    id: "ch-baseline-first",
    title: "Beat the dumbest possible model",
    brief: "Before tuning anything, establish the score of a model that ignores the features entirely.",
    steps: [
      "Split your data once and set the test set aside.",
      "Predict the majority class (or the mean, for regression) and record the metric.",
      "Fit one simple model — logistic or linear regression — and compare.",
      "If the gap is small, the problem is your features, not your algorithm.",
    ],
    category: "ml",
    difficulty: "beginner",
  },
  {
    id: "ch-one-chart",
    title: "One chart, one sentence",
    brief: "Reduce a whole analysis to a single chart whose title states the finding rather than the variables.",
    steps: [
      "Write the conclusion as a sentence first.",
      "Choose the chart type that makes that sentence visible in under three seconds.",
      "Delete every element that does not support the sentence.",
      "Use the sentence as the chart title.",
    ],
    category: "visualization",
    difficulty: "intermediate",
  },
  {
    id: "ch-sql-window",
    title: "Rewrite a self-join as a window function",
    brief: "Find a query in your codebase that joins a table to itself to compare rows, and replace it.",
    steps: [
      "Identify what the self-join computes: a previous value, a rank or a running total.",
      "Map it to LAG, RANK or SUM ... OVER.",
      "Compare row counts and a checksum of the results.",
      "Compare the query plans and note the difference.",
    ],
    category: "data",
    difficulty: "advanced",
  },
  {
    id: "ch-explain-to-finance",
    title: "Explain your last result without numbers",
    brief: "Practise the skill that actually gets analyses adopted.",
    steps: [
      "Describe the finding in two sentences with no figures.",
      "State the one decision it should change.",
      "Name the biggest reason it could be wrong.",
      "Say what you would measure next to find out.",
    ],
    category: "career",
    difficulty: "beginner",
  },
];
